spring:
  application:
    name: rollback-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      database: rollback-manager
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 9095

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

